<?php namespace App\Http\Middleware;

use Closure;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;

class VerifyCsrfToken extends BaseVerifier {

	/**
	 * Handle an incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  \Closure  $next
	 * @return mixed
	 */
	public function handle($request, Closure $next)
	{
		return parent::handle($request, $next);
	}

	protected function tokensMatch($request)
	{
		$token = $request->ajax()? $request->header('X-CSRF-Token'):$request->input("_token");
		$x= parent::tokensMatch($request);
		if(!$x)//si no coincide se devuelve el Retirado para que redireccione la página
			return "Retirado";

		return $x;  // TODO: Change the autogenerated stub
		//return $request->session()->token() == $token;
	}

}
